version: '0.0.{build}'

image: Visual Studio 2017
platform: Any CPU
configuration: Release

before_build:
- appveyor-retry dotnet restore

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.Core.UnitTests" -c %CONFIGURATION% -f netcoreapp2.0 -o bin\test

test_script:
- vstest.console /logger:Appveyor "Source\BreakingBit.Hitmeister.Core.UnitTests\bin\test\BreakingBit.Hitmeister.Core.UnitTests.dll"
