version: '0.0.{build}'

image: Visual Studio 2017
configuration: Debug

environment:
  GithubEmail: michael.herwig@hotmail.de
  GithubUsername: michael-herwig
  GithubPersonalAccessToken:
    secure: VYkVbCCsnfqbtR6PYtRtQcrMZtiLeMKw0Uhfjjn0R+IgnKYWRs2FSA7LzEAcnhka

init:
  - git config --global core.autocrlf true

before_build:
- choco install opencover.portable
- choco install docfx
- choco install wkhtmltopdf
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- appveyor-retry dotnet restore

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.Core.UnitTests" -c %CONFIGURATION% -f netcoreapp2.0 -o bin\test

- dotnet build "Source\BreakingBit.Hitmeister.API" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.API.UnitTests" -c %CONFIGURATION% -f netcoreapp2.0 -o bin\test

test_script:
- OpenCover.Console.exe -register:user -target:VsTest.Console.exe "-targetargs:/Logger:Appveyor Source\BreakingBit.Hitmeister.Core.UnitTests\bin\test\BreakingBit.Hitmeister.Core.UnitTests.dll Source\BreakingBit.Hitmeister.API.UnitTests\bin\test\BreakingBit.Hitmeister.API.UnitTests.dll" "-filter:+[BreakingBit.Hitmeister*]* -[BreakingBit.Hitmeister.*.UnitTests*]*" -output:coverage.xml -oldstyle

after_test:
- codecov -f "coverage.xml"
- docfx ./Documentation/docfx.json --build
- ps: ./Scripts/CI/PushGhPages.ps1