version: '0.0.{build}'

configuration:
- Debug
# - Release

before_build:
- appveyor-retry dotnet restore -v Minimal

build:
  project: BreakingBit.Hitmeister.sln
  parallel: true

cache:
- '%USERPROFILE%\.nuget\packages'