version: '0.0.{build}'

image: Visual Studio 2017
configuration: Release

environment:
  GithubEmail: michael.herwig@hotmail.de
  GithubUsername: michael-herwig
  GithubPersonalAccessToken:
    secure: VYkVbCCsnfqbtR6PYtRtQcrMZtiLeMKw0Uhfjjn0R+IgnKYWRs2FSA7LzEAcnhka
  SonarQubeAccessToken:
    secure: 5wNab+zPWl30NBO72SsNBTiUPDrzKHKJSUdj1vI+2GE5eLBNIgQT9qTUYCiX0CfJ
  framework: netcoreapp2.0

init:
  - git config --global core.autocrlf true

install:
- choco install opencover.portable
- choco install docfx
- choco install "msbuild-sonarqube-runner"

before_build:
- appveyor-retry dotnet restore
- SonarQube.Scanner.MSBuild.exe begin /k:"Hitmeister" /d:sonar.organization="breakingbit" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SonarQubeAccessToken% /d:sonar.branch=%APPVEYOR_REPO_BRANCH:#=% /d:sonar.cs.opencover.reportsPaths=coverage_unit.xml

build_script:
- dotnet build -c %CONFIGURATION% -f %FRAMEWORK%
- docfx ./Documentation/docfx.json --build

test_script:
- OpenCover.Console.exe -register:user -target:VsTest.Console.exe "-targetargs:/Logger:Appveyor Source\BreakingBit.Hitmeister.Core.UnitTests\bin\%CONFIGURATION%\%FRAMEWORK%\BreakingBit.Hitmeister.Core.UnitTests.dll Source\BreakingBit.Hitmeister.API.UnitTests\bin\%CONFIGURATION%\%FRAMEWORK%\BreakingBit.Hitmeister.API.UnitTests.dll" "-filter:+[BreakingBit.Hitmeister*]* -[BreakingBit.Hitmeister.*.UnitTests*]*" -output:coverage_unit.xml -oldstyle

after_test:
- SonarQube.Scanner.MSBuild.exe end /d:sonar.login=%SonarQubeAccessToken%
- ps: ./Scripts/CI/PushGhPages.ps1