version: '0.0.{build}'

image: Visual Studio 2017
configuration: Debug

init:
  - git config --global core.autocrlf true

before_build:
- choco install opencover.portable
- choco install codecov
- appveyor-retry dotnet restore

build_script:
- dotnet build -c %CONFIGURATION%

test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:VsTest.Console.exe "-targetargs:/Logger:Appveyor Source\BreakingBit.Hitmeister.Core.UnitTests\bin\test\BreakingBit.Hitmeister.Core.UnitTests.dll Source\BreakingBit.Hitmeister.API.UnitTests\bin\test\BreakingBit.Hitmeister.API.UnitTests.dll" "-filter:+[BreakingBit.Hitmeister*]*" -output:coverage.xml -oldstyle

after_test:
- codecov -f "coverage.xml"
