version: '0.0.{build}'

configuration:
- Debug
# - Release

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION% --no-dependencies
- dotnet build "Source\BreakingBit.Hitmeister.API" -c %CONFIGURATION% --no-dependencies

test:
  assemblies:
  - '**\*.UnitTests.dll'

cache:
- '%USERPROFILE%\.nuget\packages'