version: '0.0.{build}'

configuration:
- Debug
- Release

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION% --no-dependencies
- dotnet build "Source\BreakingBit.Hitmeister.API" -c %CONFIGURATION% --no-dependencies

test_script:
- dotnet test "Source\BreakingBit.Hitmeister.Core.UnitTests" -c %CONFIGURATION%
- dotnet test "Source\BreakingBit.Hitmeister.API.UnitTests" -c %CONFIGURATION%

cache:
- '%USERPROFILE%\.nuget\packages'