version: '0.0.{build}'

image: Visual Studio 2017
configuration: Release

init:
  - git config --global core.autocrlf true

before_build:
- appveyor-retry dotnet restore

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.Core.UnitTests" -c %CONFIGURATION% -f netcoreapp2.0 -o bin\test
- dotnet build "Source\BreakingBit.Hitmeister.API" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.API.UnitTests" -c %CONFIGURATION% -f netcoreapp2.0 -o bin\test

test_script:
- vstest.console /logger:Appveyor "Source\BreakingBit.Hitmeister.Core.UnitTests\bin\test\BreakingBit.Hitmeister.Core.UnitTests.dll"
- vstest.console /logger:Appveyor "Source\BreakingBit.Hitmeister.API.UnitTests\bin\test\BreakingBit.Hitmeister.API.UnitTests.dll"
