version: '0.0.{build}'

image: Visual Studio 2017
platform: Any CPU
configuration: Release

before_build:
- appveyor-retry dotnet restore

build_script:
- dotnet build "Source\BreakingBit.Hitmeister.Core" -c %CONFIGURATION%
- dotnet build "Source\BreakingBit.Hitmeister.Core.UnitTests" -c %CONFIGURATION%

test_script:
- vstest.console /logger:Appveyor 'Source\BreakingBit.Hitmeister.Core.UnitTests\obj\Release\netcoreapp2.0\BreakingBit.Hitmeister.Core.UnitTests.dll'
