version: '0.0.{build}'

configuration:
- Debug
# - Release

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "BreakingBit.Hitmeister" --configuration  %CONFIGURATION%

test_script:
- dotnet test

cache:
- '%USERPROFILE%\.nuget\packages'